### PR TITLE
Improve postgres server support

### PR DESCRIPTION
**Pull request by drrzmr**

### CODE REVIEW

**Comment by vitorabner** [comment]
It would be nice to put the "Usage" section showing how to build and use the project. In the same way we did in "Examples" section on escriba library: https://github.com/pagarme/

What do you think?

**Comment by drrzmr** [comment]
Great! But I guess that the project is only on beginning right now and a full usage doc will make sense when the project come to be more mature. But if you see some specific point that a details must be better explained, please let me know :)

**Comment by vitorabner** [comment]
Nice! I can help with this in the future. Right now I'm building and running the project to check if it's ok. I reviewed the code and seems perfect.

**Comment by jonatasnona** [comment]
i think you should remove all patches related with replication slot in this PR.
we can create another task later to this subject.

what do you think?

**Pull request merged**
